name: Static Analysis

on:
  push:
  pull_request:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R package dependencies
      run: |
        install.packages('devtools')
        devtools::install_deps(dependencies = TRUE)
        install.packages('lintr')

    - name: Run lintr
      run: |
        R -e "lintr::lint_dir()"
